-- One-time seed: restore Chris's existing collection after the switch to
-- per-user, database-backed ownership. Run this ONCE, after:
--   1. supabase/schema.sql has been run, and
--   2. you have signed up for an account through the app's own login form
--      using chriswolfesq@gmail.com (the admin email).
--
-- It looks your user up by email, so it does not matter what your user id
-- turns out to be. Re-running is safe -- it upserts, it does not duplicate.

insert into public.user_collections (user_id, bobblehead_id, team_slug, owned)
select u.id, v.bobblehead_id, v.team_slug, true
from auth.users u
cross join (
  values
    ('lawrence-butler-2025', 'athletics'),
    ('mason-miller-2025', 'athletics'),
    ('brent-rooker-2025', 'athletics'),
    ('brent-rooker-silver-slugger-2025', 'athletics'),
    ('vida-blue-2024', 'athletics'),
    ('rollie-fingers-2024', 'athletics'),
    ('mark-kotsay-mandalorian-star-wars-2023', 'athletics'),
    ('ramon-laser-laureano-2019', 'athletics'),
    ('mike-fiers-no-hitter-2019', 'athletics'),
    ('matt-chapman-gold-glove-2019', 'athletics'),
    ('sean-manaea-no-hitter-2018', 'athletics'),
    ('bob-melvin-2017', 'athletics'),
    ('josh-donaldson-tarp-catch-diorama-2014', 'athletics'),
    ('ray-fosse-2011', 'athletics'),
    ('roy-steele-2010', 'athletics'),
    ('justin-duchscherer-all-star-2009', 'athletics'),
    ('travis-buck-2008', 'athletics'),
    ('mark-ellis-2007', 'athletics'),
    ('mike-piazza-2007', 'athletics'),
    ('milton-bradley-2007', 'athletics'),
    ('eric-chavez-6-gold-gloves-non-gold-2007', 'athletics'),
    ('frank-thomas-2006', 'athletics'),
    ('dan-haren-2006', 'athletics'),
    ('nick-swisher-left-handed-2006', 'athletics'),
    ('nick-swisher-right-handed-2006', 'athletics'),
    ('huston-street-2005-rookie-of-the-year-2006', 'athletics'),
    ('huston-street-2006', 'athletics'),
    ('jason-kendall-2005', 'athletics'),
    ('dennis-eckersly-2004', 'athletics'),
    ('vida-blue-2004', 'athletics'),
    ('carney-lansford-2004', 'athletics'),
    ('reggie-jackson-2004', 'athletics'),
    ('dave-stewart-2004-season-ticket-holders-2004', 'athletics'),
    ('ramon-hernandez-2003', 'athletics'),
    ('miguel-tejada-2002-mvp-2003', 'athletics'),
    ('jim-catfish-hunter-2002', 'athletics'),
    ('eric-chavez-gold-glove-2002', 'athletics'),
    ('tim-hudson-2002', 'athletics'),
    ('jason-giambi-2000-mvp-2001', 'athletics'),
    ('rollie-fingers-cooperstown-collection-unknown', 'athletics'),
    ('ryan-braun-50th-anniversary-2021', 'brewers'),
    ('ozzie-smith-backflip-2025', 'cardinals'),
    ('scott-rolen-2024', 'cardinals'),
    ('tyler-glasnow-2025', 'dodgers'),
    ('ron-cey-legends-of-dodger-baseball-2025', 'dodgers'),
    ('tommy-edman-2025', 'dodgers'),
    ('shohei-ohtani-50-50-sliding-2025', 'dodgers'),
    ('mookie-betts-2025', 'dodgers'),
    ('dave-roberts-2025', 'dodgers'),
    ('evan-phillips-2024', 'dodgers'),
    ('matt-kemp-2024', 'dodgers'),
    ('jason-hayward-city-connect-2024', 'dodgers'),
    ('bobby-miller-2024', 'dodgers'),
    ('tyler-glasnow-2024', 'dodgers'),
    ('shohei-ohtani-2024', 'dodgers'),
    ('walker-buehler-2024', 'dodgers'),
    ('brusdar-graterol-2024', 'dodgers'),
    ('joe-kelly-2023', 'dodgers'),
    ('dave-roberts-2023', 'dodgers'),
    ('austin-barnes-2023', 'dodgers'),
    ('james-outman-miguel-vargas-2023', 'dodgers'),
    ('chris-taylor-2023', 'dodgers'),
    ('j-d-martinez-2023', 'dodgers'),
    ('caleb-williams-2023', 'dodgers'),
    ('tony-gonsolin-2023', 'dodgers'),
    ('gavin-lux-2023', 'dodgers'),
    ('dustin-may-2023', 'dodgers'),
    ('manny-mota-legends-of-dodger-baseball-2023', 'dodgers'),
    ('julio-urias-2023', 'dodgers'),
    ('dustin-may-2022', 'dodgers'),
    ('gil-hodges-hall-of-fame-2022', 'dodgers'),
    ('walker-buehler-2022', 'dodgers'),
    ('maury-wills-legends-of-dodger-baseball-2022', 'dodgers'),
    ('walker-buehler-2021', 'dodgers'),
    ('cody-bellinger-nlds-game-1-home-white-uniform-2019', 'dodgers'),
    ('cody-bellinger-nlds-game-1-away-grey-uniform-2019', 'dodgers'),
    ('alex-verdugo-2019', 'dodgers'),
    ('tommy-lasorda-2019', 'dodgers'),
    ('rich-hill-2018', 'dodgers'),
    ('alex-wood-2018', 'dodgers'),
    ('clayton-kershaw-60th-anniversary-retro-2018', 'dodgers'),
    ('dave-roberts-manager-of-the-year-2017', 'dodgers'),
    ('andre-ethier-2017', 'dodgers'),
    ('kenley-jansen-2017', 'dodgers'),
    ('vin-scully-2016', 'dodgers'),
    ('dusty-baker-2016', 'dodgers'),
    ('yasiel-puig-diving-2015', 'dodgers'),
    ('clayton-kershaw-2015', 'dodgers'),
    ('babe-ruth-2014', 'dodgers'),
    ('a-j-ellis-2014', 'dodgers'),
    ('zack-greinke-2014', 'dodgers'),
    ('baker-cey-garvey-smith-original-30-hr-club-2014', 'dodgers'),
    ('brian-wilson-fear-the-beard-2014', 'dodgers'),
    ('yasiel-puig-2014', 'dodgers'),
    ('magic-johnson-2013', 'dodgers'),
    ('rick-monday-saves-the-flag-2013', 'dodgers'),
    ('vin-scully-2013', 'dodgers'),
    ('adrian-gonzalez-2013', 'dodgers'),
    ('sandy-koufax-2013', 'dodgers'),
    ('matt-kemp-2013', 'dodgers'),
    ('hanley-ramirez-i-see-you-2013', 'dodgers'),
    ('mike-scioscia-all-time-dodger-leader-games-caught-2012', 'dodgers'),
    ('don-drysdale-maury-wills-cy-young-dual-2012', 'dodgers'),
    ('duke-snider-2011', 'dodgers'),
    ('andre-ethier-brooklyn-throwback-2011', 'dodgers'),
    ('hong-chih-kuo-2011', 'dodgers'),
    ('don-mattingly-2011', 'dodgers'),
    ('james-loney-2010', 'dodgers'),
    ('jonathan-broxton-2010', 'dodgers'),
    ('matt-kemp-2009', 'dodgers'),
    ('manny-ramirez-2009', 'dodgers'),
    ('casey-blake-2009', 'dodgers'),
    ('joe-beimel-2008', 'dodgers'),
    ('brad-penny-2008', 'dodgers'),
    ('takashi-saito-2008', 'dodgers'),
    ('joe-torre-2008', 'dodgers'),
    ('russell-martin-2007', 'dodgers'),
    ('rafael-furcal-2007', 'dodgers'),
    ('fernando-valenzuela-2006', 'dodgers'),
    ('jeff-kent-2005', 'dodgers'),
    ('cesar-izturis-2005', 'dodgers'),
    ('don-newcombe-1956-cy-young-2004', 'dodgers'),
    ('fred-mcgriff-2003', 'dodgers'),
    ('brian-jordan-2003', 'dodgers'),
    ('eric-gagne-2003', 'dodgers'),
    ('hideo-nomo-2002', 'dodgers'),
    ('shawn-green-2002', 'dodgers'),
    ('paul-loduca-2002', 'dodgers'),
    ('kirk-gibson-2001', 'dodgers'),
    ('tommy-lasorda-2001', 'dodgers'),
    ('frank-robinson-2017', 'giants'),
    ('jeremy-affeldt-2015', 'giants'),
    ('barry-zito-2013', 'giants'),
    ('macklemore-2014', 'mariners'),
    ('ichiro-suzuki-2008', 'mariners'),
    ('stephen-strasburg-2012', 'nationals'),
    ('trevor-hoffman-2018', 'padres'),
    ('roberto-clemente-2001', 'pirates'),
    ('yasiel-puig-wild-horse-2019', 'reds'),
    ('whit-merrifield-two-hit-whit-2018', 'royals'),
    ('prince-fielder-2012', 'tigers'),
    ('harmon-killebrew-sth-red-variant-2006', 'twins')
) as v (bobblehead_id, team_slug)
where u.email = 'chriswolfesq@gmail.com'
on conflict (user_id, bobblehead_id) do update
  set owned = true, updated_at = now();
