// Generated by scripts/import-team-banners.mjs — do not edit by hand.
//
// The pixel size of every public/team-banners/<slug>.png. The team page needs a
// width and height on the <Image> to reserve the box before the bytes land, and
// the cards aren't all the same shape, so a single hardcoded pair would squash
// the tall ones.
export const TEAM_BANNERS: Record<string, { width: number; height: number }> = {
  "orioles": { width: 1942, height: 809 },
  "red-sox": { width: 1942, height: 809 },
  "yankees": { width: 1942, height: 809 },
  "rays": { width: 1672, height: 941 },
  "blue-jays": { width: 1610, height: 879 },
  "white-sox": { width: 1942, height: 809 },
  "guardians": { width: 1942, height: 809 },
  "tigers": { width: 1942, height: 809 },
  "royals": { width: 1942, height: 809 },
  "twins": { width: 1942, height: 809 },
  "astros": { width: 1942, height: 809 },
  "angels": { width: 1942, height: 809 },
  "athletics": { width: 1674, height: 844 },
  "mariners": { width: 1906, height: 773 },
  "rangers": { width: 1942, height: 809 },
  "braves": { width: 1920, height: 819 },
  "marlins": { width: 1919, height: 820 },
  "mets": { width: 1892, height: 791 },
  "phillies": { width: 1890, height: 757 },
  "nationals": { width: 1942, height: 809 },
  "cubs": { width: 1898, height: 765 },
  "reds": { width: 1890, height: 789 },
  "brewers": { width: 1942, height: 809 },
  "pirates": { width: 1942, height: 809 },
  "cardinals": { width: 1942, height: 809 },
  "diamondbacks": { width: 1942, height: 809 },
  "rockies": { width: 1942, height: 809 },
  "dodgers": { width: 1942, height: 809 },
  "padres": { width: 1942, height: 809 },
  "giants": { width: 1643, height: 879 },
};
