import { feature, merge } from "topojson-client";
import { geoAlbersUsa, geoPath } from "d3-geo";
import fs from "node:fs";
import statesTopology from "../node_modules/us-atlas/states-10m.json" with { type: "json" };
import { TEAM_COORDS } from "./team-coords.mjs";

const WIDTH = 975;
const HEIGHT = 610;

// non-contiguous territories/states to exclude (Alaska, Hawaii, Puerto Rico) —
// the reference art only shows the contiguous US.
const EXCLUDE_IDS = new Set(["02", "15", "72"]);

const projection = geoAlbersUsa().scale(1300).translate([487.5, 305]);
const pathGen = geoPath(projection);

const statesFC = feature(statesTopology, statesTopology.objects.states);

const statePaths = statesFC.features
  .filter((f) => !EXCLUDE_IDS.has(f.id))
  .map((f) => ({ id: f.id, name: f.properties.name, d: pathGen(f) }))
  .filter((s) => s.d);

const contiguousGeometries = statesTopology.objects.states.geometries.filter(
  (g) => !EXCLUDE_IDS.has(g.id)
);
const nationOutlineGeom = merge(statesTopology, contiguousGeometries);
const nationD = pathGen(nationOutlineGeom);

// raw projected pixel positions (in the 975x610 projection space)
const rawPoints = Object.entries(TEAM_COORDS).map(([slug, [lon, lat]]) => {
  const p = projection([lon, lat]);
  return { slug, x: p[0], y: p[1] };
});

// Simple iterative bounding-box declutter: nudge apart any two markers whose
// footprints (marker + a little breathing room) would overlap once rendered,
// while keeping everyone as close as possible to their true geographic spot.
const MARKER_W = 34;
const MARKER_H = 48;
const ITERATIONS = 400;
const STEP = 0.6;

for (let iter = 0; iter < ITERATIONS; iter++) {
  let moved = false;
  for (let i = 0; i < rawPoints.length; i++) {
    for (let j = i + 1; j < rawPoints.length; j++) {
      const a = rawPoints[i];
      const b = rawPoints[j];
      let dx = b.x - a.x;
      let dy = b.y - a.y;
      if (dx === 0 && dy === 0) {
        dx = (i % 2 === 0 ? 1 : -1) * 0.01;
        dy = (j % 2 === 0 ? 1 : -1) * 0.01;
      }
      const overlapX = MARKER_W - Math.abs(dx);
      const overlapY = MARKER_H - Math.abs(dy);
      if (overlapX > 0 && overlapY > 0) {
        moved = true;
        // push along whichever axis has the smaller overlap (cheaper separation)
        if (overlapX < overlapY) {
          const push = (overlapX / 2 + 0.3) * STEP * Math.sign(dx || 1);
          a.x -= push;
          b.x += push;
        } else {
          const push = (overlapY / 2 + 0.3) * STEP * Math.sign(dy || 1);
          a.y -= push;
          b.y += push;
        }
      }
    }
  }
  if (!moved) break;
}

const teamPositions = Object.fromEntries(
  rawPoints.map(({ slug, x, y }) => [
    slug,
    { x: +((x / WIDTH) * 100).toFixed(2), y: +((y / HEIGHT) * 100).toFixed(2) },
  ])
);

fs.writeFileSync(
  new URL("../lib/usStatePaths.ts", import.meta.url),
  `// Generated by scripts/generate-map.mjs — do not hand-edit.\n` +
    `export const MAP_VIEWBOX = "0 0 ${WIDTH} ${HEIGHT}";\n\n` +
    `export interface StatePath {\n  id: string;\n  name: string;\n  d: string;\n}\n\n` +
    `export const STATE_PATHS: StatePath[] = ${JSON.stringify(statePaths, null, 2)};\n\n` +
    `export const NATION_OUTLINE = ${JSON.stringify(nationD)};\n`
);

fs.writeFileSync(
  new URL("../scripts/team-positions.json", import.meta.url),
  JSON.stringify(teamPositions, null, 2)
);

console.log(`Wrote ${statePaths.length} state paths.`);
console.log("Team positions:", teamPositions);
